# Generated by Django 4.1.7 on 2023-03-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='category',
        ),
        migrations.RemoveField(
            model_name='waste',
            name='category',
        ),
        migrations.RemoveField(
            model_name='waste',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='waste',
            name='venue',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='MeasurementUnit',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.DeleteModel(
            name='Waste',
        ),
    ]
