# Generated by Django 4.1.7 on 2023-03-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_waste_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='title',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='text',
            field=models.TextField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
