# Generated by Django 4.1.7 on 2023-03-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_recommendation_title_recommendation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='title',
            field=models.CharField(blank=True, default='Заголовок', max_length=150, verbose_name='Заголовок'),
        ),
    ]
