# Generated by Django 4.1.7 on 2023-03-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_recommendation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='preview_text',
            field=models.TextField(default='Текст', verbose_name='Текст'),
        ),
    ]
