# Generated by Django 4.1.7 on 2023-03-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_recommendation_preview_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='preview_text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
