# Generated by Django 4.1.7 on 2023-03-25 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_recommendation_preview_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', unique=True, verbose_name='Категория'),
        ),
    ]
