# Generated by Django 4.1.7 on 2023-03-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
