# Generated by Django 4.1.7 on 2023-03-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_profileimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Рисунок'),
        ),
    ]
