# Generated by Django 4.1.7 on 2023-03-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_badge_task_alter_profileimage_image_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='category',
            field=models.ManyToManyField(to='main.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='badge',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Вес'),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
