# Generated by Django 4.1.7 on 2023-03-25 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_badge_options_userbadge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='category',
        ),
        migrations.AddField(
            model_name='badge',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категории'),
            preserve_default=False,
        ),
    ]
