# Generated by Django 4.1.7 on 2023-03-26 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_userbadge_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.badge', verbose_name='Достижение'),
        ),
    ]
