# Generated by Django 4.1.7 on 2023-03-26 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_userbadge_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste', to='main.category', verbose_name='Категория'),
        ),
    ]
